package com.abc.rule.user.ipm
import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.common.OutputDisplay;
import com.zhsq.biz.common.AuthAlgorithm;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.sysdate.SystemDateTimeManager;
import com.zhsq.biz.common.AuthUtil;
import java.util.Collection;
import com.zhsq.biz.worktask.algorithm.TaskIntrospection;
import com.zhsq.biz.constant.user.UserItem;
import com.zhsq.biz.user.algorithm.UserIntrospection;
import com.zhsq.biz.constant.CommonAlgorithm;
global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;
rule "密码加密" 
	salience 10 
	
when
	$passwordFA:FuseAttribute(name == UserItem.原始密码,CommonAlgorithm.isLawfulPassword(value));
then
	attributeList.add(AttributeFactory.newInstance(UserItem.加密密码,CommonAlgorithm.encryptMD5($passwordFA.getValue())));
	attributeList.add(AttributeFactory.newInstance(UserItem.原始密码,null));
end








 