package com.abc.rule.worktask.twoipm

import com.abc.rrc.record.Attribute;
import com.zhsq.biz.constant.CommonAlgorithm;
import com.zhsq.biz.constant.family.FamilyItem;
import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.model.enun.ValueType;
import com.zhsq.biz.constant.EnumKeyValue;
import com.abc.fuse.improve.attribute.label.FuseLabelAttribute;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
import com.zhsq.biz.common.CommonCalculation;
import java.util.Date;
import com.abc.rrc.factory.DBAttributeFactory;
import com.zhsq.biz.constant.people.PeopleItem;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.constant.BaseConstant;
import com.abc.ops.builder.RecordRelationOpsBuilder;
import com.zhsq.biz.constant.RelationType;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.transfer.builder.IRootRecordBuilder;
import com.abc.transfer.builder.RootRecordBuilderFactory;
import com.abc.rrc.record.RootRecord;
import com.abc.sysdate.SystemDateTimeManager;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.abc.relation.RelationCorrelation;
import com.abc.relation.RecordRelation;
import com.abc.fuse.improve.attribute.OpsAttribute;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.abc.fuse.improve.attribute.leaf.OpsLeafAttribute;
import com.zhsq.biz.user.algorithm.UserIntrospection;
import com.zhsq.biz.constant.user.UserItem;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "设置组织名称"//和用户有关系的组织名称设置到用户【组织名称】字段中
	when
		RecordRelation(type==RelationType.RR_用户_属于组织_组织,left==recordCode);
	then 
		String orgNames = UserIntrospection.getOrgName(recordComplexus, recordName, recordCode);
		Attribute attrbute=DBAttributeFactory.newInstance(UserItem.组织名称,orgNames);
		attributeList.add(attrbute);
end

