package com.abc.rule.people.identity.query

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.abc.model.enun.ValueType;
import com.abc.rrc.query.criteria.CommonSymbol;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.people.PeopleItem;

global java.lang.String recordName;
global com.abc.rrc.query.criteria.BizzCriteriaFactory bizzCriteriaFactory;

rule "姓名 and 身份证号 criteria" 
	activation-group "people查询条件"
	salience 9  
when
    $nameFB:FuseAttribute(name==PeopleItem.姓名,CommonCalculation.isBasicLawful((String)getValue(ValueType.STRING)));
    FuseLeafAttribute(name==PeopleItem.证件信息_证件类型,CommonCalculation.isBasicLawful((String)getValue(ValueType.STRING)), getValue(ValueType.INT) == EnumKeyValue.ENUM_证件类型_身份证, $leafCode:leafCode);
	$IdFB: FuseLeafAttribute(name==PeopleItem.证件信息_证件号码,CommonCalculation.isBasicLawful((String)getValue(ValueType.STRING)), $leafCode==leafCode);
then 
	bizzCriteriaFactory.addCriteria($nameFB.getAttribute(), CommonSymbol.EQUAL);
	bizzCriteriaFactory.addCriteria($IdFB.getAttribute(), CommonSymbol.EQUAL);
end

rule "姓名 and 户籍地址 criteria" 
	activation-group "people查询条件"
	salience 8  
when
    $nameFA:FuseAttribute(name==PeopleItem.姓名,CommonCalculation.isBasicLawful((String)getValue(ValueType.STRING)));
    $siteFB:FuseAttribute(name == PeopleItem.户籍所在地,CommonCalculation.isBasicLawful((String)getValue(ValueType.STRING)));
then      
	bizzCriteriaFactory.addCriteria($nameFA.getAttribute(), CommonSymbol.EQUAL);
	bizzCriteriaFactory.addCriteria($siteFB.getAttribute(), CommonSymbol.EQUAL);
end
