package com.abc.rule.worktask.ipm.tipmTimer

import com.abc.rrc.record.Attribute;
import com.zhsq.biz.constant.CommonAlgorithm;
import com.zhsq.biz.constant.family.FamilyItem;
import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.model.enun.ValueType;
import com.zhsq.biz.constant.EnumKeyValue;
import com.abc.fuse.improve.attribute.label.FuseLabelAttribute;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
import com.zhsq.biz.common.CommonCalculation;
import java.util.Date;
import com.abc.rrc.factory.DBAttributeFactory;
import com.zhsq.biz.constant.people.PeopleItem;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.constant.BaseConstant;
import com.abc.ops.builder.RecordRelationOpsBuilder;
import com.zhsq.biz.constant.RelationType;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.transfer.builder.IRootRecordBuilder;
import com.abc.transfer.builder.RootRecordBuilderFactory;
import com.abc.rrc.record.RootRecord;
import com.abc.sysdate.SystemDateTimeManager;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.abc.relation.RelationCorrelation;
import com.abc.relation.RecordRelation;
import com.abc.fuse.improve.attribute.OpsAttribute;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.abc.fuse.improve.attribute.leaf.OpsLeafAttribute;
import com.zhsq.biz.worktask.algorithm.TaskIntrospection;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "超时任务标记"//处理中的任务进行超时标记
	salience 8
when
	$taskD:FuseAttribute( name==WorkTaskItem.任务状态, getValue(ValueType.INT)==EnumKeyValue.ENUM_任务状态_处理中);
	$taskE:FuseAttribute( name==WorkTaskItem.任务结束时间,CommonCalculation.isBasicLawful(getValue(ValueType.STRING)));
	$taskF:FuseAttribute( name==WorkTaskItem.任务是否超时,getValue(ValueType.INT)!=EnumKeyValue.ENUM_是否_是) or (not FuseAttribute(name==WorkTaskItem.任务是否超时))
	eval(TaskIntrospection.inspectTimeOut((String)$taskE.getValue(ValueType.STRING)))
then  
	Attribute taskF = DBAttributeFactory.newInstance(WorkTaskItem.任务是否超时, EnumKeyValue.ENUM_是否_是);
	attributeList.add(taskF);
end

